#ifndef lint	/* .../config.c */
#define _AC_NAME config_c
#define _AC_NO_MAIN "%Z% Copyright (c) ???, All Rights Reserved.  {Apple version %I% %E% %U%}"
#include <apple_notice.h>

#ifdef _AC_HISTORY
#endif		/* _AC_HISTORY */
#endif		/* lint */

#
/*
 * config.c (config.proto)
 *
 * Copyright (c) 1985 Adobe Systems Incorporated
 *
 * defines global string constants for default directories
 * config.c is generated by the Makefile doing a "sed" on config.proto
 *
 * RCSID: $Header: config.proto,v 2.1 85/11/24 11:48:50 shore Rel $
 *
 * @(#)Copyright Apple Computer 1987\tVersion 1.1 of config.proto on 87/05/04 19:06:13
 *
 * Edit History:
 * Andrew Shore: Tue May 14 10:12:14 1985
 * End Edit History.
 *
 * RCSLOG:
 * $Log:	config.proto,v $
 * Revision 2.1  85/11/24  11:48:50  shore
 * Product Release 2.0
 * 
 * Revision 1.3  85/11/20  00:01:25  shore
 * Removed some printer-specific things to shell interface/environment
 * for Release 2.0
 * 
 * Revision 1.2  85/05/14  11:21:11  shore
 * 
 * 
 *
 */

/* note the trailing / on TroffFontDir are important here */
char LibDir[]	= "/usr/lib/ps";
char TroffFontDir[] = "/usr/lib/ps/troff.font/";
char DitDir[]	= "/usr/lib/font";
char TempDir[]	= "/usr/tmp";
